### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by player0-gg** [player0-gg/docker-flask-web#1]
### Links
-  [Project device](https://github.com/player0-gg/docker-pyqt-raspberrypi)
-  [Project server](https://github.com/player0-gg/docker-flask-web)
### Working on
- [ ] **server**: example Kubernetes Docker Flask Web on MacOs: simple service
* Issue: no response from pods (DNS config?)

### TODO
- [ ] **other**: read [Flask mega tutorial](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world)
- [ ] **server**: using new app structure due to Flask mega tutorial (optional)
- [ ] **server**: integration OpenCV simple module
- [ ] **server**: integration OpenCV &  TensorFlow detect simple objects from images
- [ ] **server**: example Angular simple module
- [ ] **server**: service & deployment all
- [ ] **device**: integration PyQtGraph simple module
- [ ] **device**: integration OpenCV simple module using camera
- [ ] **device**: integration TensorFlow detect simple objects from images

### Done
- [x] **device**: example Docker PyQt5 on Raspberry Pi
* PyQt5: simple app
* Docker: run image on Raspberry Pi
* => Done in [commit](https://github.com/player0-gg/docker-pyqt-raspberrypi/commit/bc7344a6dc1bb1e5fca563cdada9a0afb671d200)
- [x] **server**: example Docker Flask Web on MacOs
* Docker: run image local
* Done in [commit](https://github.com/player0-gg/docker-flask-web/commit/5e5d700125881b066291b9ef658a47cb7378085c)
- [x] **server**: example Kubernetes Docker Flask Web on MacOs: simple deployment
* Done in [commit](https://github.com/player0-gg/docker-flask-web/commit/befa2b37779a15a173579ed509821f000f2f6c84)

**Comment by player0-gg** [comment]
move to https://github.com/player0-gg/learning/
